/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import Classes.Administrator;
import static java.awt.SystemColor.menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author User
 */
public class JF_Administrator extends javax.swing.JFrame {

    private Administrator admin;
    private JPopupMenu usernameMenu;
    
    /**
     * Creates new form JF_Administrator
     */
    

    
    public JF_Administrator() {
        Administrator admin = new Administrator("Guest", "12345678", "Guest", "123456789012");
        this.admin = admin;
        initializeUsernameMenu();
        initComponents();
        JL_Name.setText("Guest");
        JB_Username.setText("Guest");
    }
    public JF_Administrator(Administrator admin) {
        this.admin = admin;
        initializeUsernameMenu();
        initComponents();
        JL_Name.setText(admin.getName());
        JB_Username.setText(admin.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Name = new javax.swing.JLabel();
        JBUserRegistration = new javax.swing.JButton();
        JBTopUp = new javax.swing.JButton();
        JB_Username = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_Name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JL_Name.setText("Administrator");

        JBUserRegistration.setText("User Registration");
        JBUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUserRegistrationActionPerformed(evt);
            }
        });

        JBTopUp.setText("Customer Top-Up");
        JBTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTopUpActionPerformed(evt);
            }
        });

        JB_Username.setText("LogOut");
        JB_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_UsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(JL_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(JB_Username))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBUserRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(JL_Name))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JB_Username)))
                .addGap(18, 18, 18)
                .addComponent(JBUserRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JBTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUserRegistrationActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame newFrame = new JF_UserRegistration(admin);
        newFrame.setVisible(true);
    }//GEN-LAST:event_JBUserRegistrationActionPerformed

    private void JB_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_UsernameActionPerformed
        // TODO add your handling code here:
        usernameMenu.show(JB_Username, 0, JB_Username.getHeight()); // Show the menu below the button
    }//GEN-LAST:event_JB_UsernameActionPerformed

    private void JBTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTopUpActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame newFrame = new JF_CustomerTopUp(admin);
        newFrame.setVisible(true);
    }//GEN-LAST:event_JBTopUpActionPerformed
    
    private void initializeUsernameMenu() {
        usernameMenu = new JPopupMenu();

        // Create the logout menu item
        JMenuItem logoutItem = new JMenuItem("Log Out");
        logoutItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JF_Administrator.this.dispose();
                JFrame newFrame = new JF_AdminLogin();
                newFrame.setVisible(true);
            }
        });

        // Add the logout item to the menu
        usernameMenu.add(logoutItem);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTopUp;
    private javax.swing.JButton JBUserRegistration;
    private javax.swing.JButton JB_Username;
    private javax.swing.JLabel JL_Name;
    // End of variables declaration//GEN-END:variables
}
