/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import Classes.Administrator;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JF_CustomerRegistration extends javax.swing.JFrame {

        private Administrator admin;
        private String VendorUsername;
    /**
     * Creates new form JF_VendorRegistration
     */
    public JF_CustomerRegistration() {
        initComponents();
        
        String filePath = Config.getFilePath("UserListPath");
        File file = new File(filePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();
            Object[] tableLines = br.lines().toArray();
        
            for(int i=0 ; i < tableLines.length ; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                if (dataRow[0].equals("Vendor")){
                    String[] VendorData = {dataRow[1],dataRow[2],dataRow[3],dataRow[4],dataRow[5],dataRow[6],dataRow[7]};
                    VendorTable.addRow(VendorData);
                }else continue;
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"The Password doesn't match");
        }
    }
    
        public JF_CustomerRegistration(Administrator admin) {
        this.admin = admin;
        initComponents();
        
        String filePath = Config.getFilePath("UserListPath");
        File file = new File(filePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();
            Object[] tableLines = br.lines().toArray();
        
            for(int i=0 ; i < tableLines.length ; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                if (dataRow[0].equals("Vendor")){
                    String[] VendorData = {dataRow[1],dataRow[2],dataRow[3],dataRow[4],dataRow[5],dataRow[6],dataRow[7]};
                    VendorTable.addRow(VendorData);
                }else continue;
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"The Password doesn't match");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JFUsername = new javax.swing.JTextField();
        JFLocation = new javax.swing.JTextField();
        JFBalance = new javax.swing.JTextField();
        JFPhoneNumber = new javax.swing.JTextField();
        JFPassword = new javax.swing.JTextField();
        JFPassword2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTVendor = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        JFStoreName = new javax.swing.JTextField();
        JBAdd = new javax.swing.JButton();
        JBEdit = new javax.swing.JButton();
        JBDelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        JFName = new javax.swing.JTextField();
        JB_Back = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Vendor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Store Name :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Location :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Password :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Confirm Password :");

        JFUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFUsernameActionPerformed(evt);
            }
        });

        JFPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFPassword2ActionPerformed(evt);
            }
        });

        JTVendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Name", "PhoneNumber", "StoreName", "Location", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTVendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTVendorMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JTVendorMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(JTVendor);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Balance :");

        JBAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JBAdd.setText("Add");
        JBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAddActionPerformed(evt);
            }
        });

        JBEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JBEdit.setText("Edit");
        JBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditActionPerformed(evt);
            }
        });

        JBDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JBDelete.setText("Delete");
        JBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDeleteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Name:");

        JB_Back.setText("Back");
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JB_Back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JFPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(JFUsername)
                                    .addComponent(JFLocation)
                                    .addComponent(JFBalance)
                                    .addComponent(JFStoreName)
                                    .addComponent(JFPassword2)
                                    .addComponent(JFName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(JBAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBDelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JFPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Back)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBAdd)
                            .addComponent(JBEdit)
                            .addComponent(JBDelete))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFPassword2ActionPerformed

    private void JBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();
        String Username = JFUsername.getText();

        if (JTVendor.getSelectedRowCount() == 1) {
            String filePath = Config.getFilePath("UserListPath");
            File file = new File(filePath);
            List<String> lines = new ArrayList<>();
            String lineToRemove = "";

            try {
                BufferedReader br = new BufferedReader(new FileReader(file));
                String line;
                while ((line = br.readLine()) != null) {
                    lines.add(line);
                    String[] dataRow = line.split("/");
                    if ("Vendor".equals(dataRow[0]) && dataRow[1].equals(Username)) {
                        lineToRemove = line;
                    }
                }
                br.close();

                // Remove the identified line
                if (!lineToRemove.isEmpty()) {
                    lines.remove(lineToRemove);
                    // Write the remaining lines back to the file
                    BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                    for (String l : lines) {
                        bw.write(l + System.lineSeparator());
                    }
                    bw.close();
                    // Remove row from the table
                    VendorTable.removeRow(JTVendor.getSelectedRow());
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "File not found.");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error reading or writing file.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Haven't selected any table.");
        }
    }//GEN-LAST:event_JBDeleteActionPerformed

    private void JBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();
        if (JTVendor.getSelectedRowCount() == 1) {
        String Username = JFUsername.getText();
        String Password = JFPassword.getText();
        String Name = JFName.getText();
        String PhoneNumber = JFPhoneNumber.getText();
        String StoreName = JFStoreName.getText();
        String Location = JFLocation.getText();
        String Balance = JFBalance.getText();
        int selectedRow = JTVendor.getSelectedRow();

        VendorTable.setValueAt(Username, selectedRow, 0);
        VendorTable.setValueAt(Password, selectedRow, 1);
        VendorTable.setValueAt(Name, selectedRow, 2);
        VendorTable.setValueAt(PhoneNumber, selectedRow, 3);
        VendorTable.setValueAt(StoreName, selectedRow, 4);
        VendorTable.setValueAt(Location, selectedRow, 5);
        VendorTable.setValueAt(Balance, selectedRow, 6);

        String filePath = Config.getFilePath("UserListPath");
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            List<String> lines = new ArrayList<>();
            String line;

            // Read all lines from the file
            while ((line = br.readLine()) != null) {
                lines.add(line);
            }

            br.close();

            // Find the correct line based on the username
            for (int i = 0; i < lines.size(); i++) {
                String[] data = lines.get(i).split("/");
                if (data.length > 1 && data[1].equals(VendorUsername)) {
                    // Update the selected row data in the list
                    String userType = data[0];
                    String updatedLine = userType + "/" +
                            Username + "/" +
                            Password + "/" +
                            Name + "/" +
                            PhoneNumber + "/" +
                            StoreName + "/" +
                            Location + "/" +
                            Balance;

                    lines.set(i, updatedLine);

                    // Write the updated list back to the file
                    BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                    for (String updated : lines) {
                        bw.write(updated + "\n");
                    }

                    bw.close();

                    clearTextField();
                    
                    JFPassword2.setText("");
                    JFName.setText("");
                  
                    JOptionPane.showMessageDialog(this, "Successfully Updated!");
                    return;
                }
            }

            JOptionPane.showMessageDialog(this, "Username not found in the text file");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error updating text file: " + ex.getMessage());
        }
    } else {
        if (JTVendor.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is empty");
        } else {
            JOptionPane.showMessageDialog(this, "Haven't selected any table row");
        }
    }
    }//GEN-LAST:event_JBEditActionPerformed

   
    private void JBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAddActionPerformed
        // TODO add your handling code here:
        String Password = JFPassword.getText();
        String Password2 = JFPassword2.getText();
        String Username = JFUsername.getText();
        String StoreName = JFStoreName.getText();
        String Location = JFLocation.getText();
        String PhoneNumber = JFPhoneNumber.getText();
        if(JFUsername.getText().equals("")||JFLocation.getText().equals("")||JFBalance.getText().equals("")||JFStoreName.getText().equals("")||JFPhoneNumber.getText().equals("")||JFPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this,"please enter Complete Data");
        } else if(!Password2.equals(Password)){
            JOptionPane.showMessageDialog(this,"The Password doesn't match");
        } else if (CheckDup(Username,StoreName,Location,PhoneNumber)) {
        }else {
            
            String data[] = {JFUsername.getText(),JFPassword.getText(),JFName.getText(),JFPhoneNumber.getText(),JFStoreName.getText(),JFLocation.getText(),JFBalance.getText()};
            String data1[] = {JFUsername.getText(),JFPassword.getText(),JFName.getText(),JFPhoneNumber.getText(),JFStoreName.getText(),JFLocation.getText(),JFBalance.getText()};
            DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();

            
            VendorTable.addRow(data);
            JFUsername.setText("");
            JFLocation.setText("");
            JFBalance.setText("");
            JFStoreName.setText("");
            JFPhoneNumber.setText("");
            JFPassword.setText("");
            JFPassword2.setText("");
            JFName.setText("");
            
            String filePath = Config.getFilePath("UserListPath");
            
                   
        try (FileWriter fileWriter = new FileWriter(filePath, true);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter)) {

            // Construct the data string
            String datas = "Vendor/" + String.join("/", data1);

            // Append the data to the file
            bufferedWriter.write(datas);
            bufferedWriter.newLine();  // Add a newline for clarity or to separate entries
            bufferedWriter.flush();   // Flush the buffer to ensure data is written

            System.out.println("Data has been appended to the file.");

        } catch (IOException e) {
            e.printStackTrace();
        }
        }
        
           
        
    }//GEN-LAST:event_JBAddActionPerformed

    private void JTVendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTVendorMouseClicked

    }//GEN-LAST:event_JTVendorMouseClicked

    private void JTVendorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTVendorMouseReleased
        // TODO add your handling code here:
        DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();
        String Username = VendorTable.getValueAt(JTVendor.getSelectedRow(), 0).toString();
        String Password = VendorTable.getValueAt(JTVendor.getSelectedRow(), 1).toString();
        String Name = VendorTable.getValueAt(JTVendor.getSelectedRow(), 2).toString();
        String PhoneNumber = VendorTable.getValueAt(JTVendor.getSelectedRow(), 3).toString();
        String StoreName = VendorTable.getValueAt(JTVendor.getSelectedRow(), 4).toString();
        String Location = VendorTable.getValueAt(JTVendor.getSelectedRow(), 5).toString();
        String Balance = VendorTable.getValueAt(JTVendor.getSelectedRow(), 6).toString();
        
        
        JFStoreName.setText(StoreName);
        JFUsername.setText(Username);
        JFPhoneNumber.setText(PhoneNumber);
        JFLocation.setText(Location);
        JFBalance.setText(Balance);
        JFName.setText(Name);
        JFPassword.setText(Password);
        
        VendorUsername = VendorTable.getValueAt(JTVendor.getSelectedRow(), 0).toString();
        
        
    }//GEN-LAST:event_JTVendorMouseReleased

   private boolean CheckDup(String Username,String StoreName,String Location,String PhoneNumber) {
    DefaultTableModel VendorTable = (DefaultTableModel) JTVendor.getModel();
    for (int i = 0; i < VendorTable.getRowCount(); i++) {
        String existingUsername = (String) VendorTable.getValueAt(i, 0);
        String existingStoreName = (String) VendorTable.getValueAt(i, 4);
        String existingLocation = (String) VendorTable.getValueAt(i, 5);
        String existingPhoneNumber = (String) VendorTable.getValueAt(i, 3);
        if (Username.equals(existingUsername)) {
            JOptionPane.showMessageDialog(this, "Username already exists. Please use a different username.");
            return true;
        } else if (StoreName.equals(existingStoreName)){
            JOptionPane.showMessageDialog(this, "StoreName already exists. Please use a different StoreName.");
            return true;
        }else if (Location.equals(existingLocation)){
            JOptionPane.showMessageDialog(this, "Location already exists. Please use a different Location.");
            return true;
        }else if (PhoneNumber.equals(existingPhoneNumber)){
            JOptionPane.showMessageDialog(this, "PhoneNumber already exists. Please use a different PhoneNumber.");
            return true;
        }
    }
    return false;
}
    private void JFUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFUsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JFUsernameActionPerformed

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame newFrame = new JF_UserRegistration(admin);
        newFrame.setVisible(true);
    }//GEN-LAST:event_JB_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_CustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdd;
    private javax.swing.JButton JBDelete;
    private javax.swing.JButton JBEdit;
    private javax.swing.JButton JB_Back;
    private javax.swing.JTextField JFBalance;
    private javax.swing.JTextField JFLocation;
    private javax.swing.JTextField JFName;
    private javax.swing.JTextField JFPassword;
    private javax.swing.JTextField JFPassword2;
    private javax.swing.JTextField JFPhoneNumber;
    private javax.swing.JTextField JFStoreName;
    private javax.swing.JTextField JFUsername;
    private javax.swing.JTable JTVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void clearTextField() {
        JFUsername.setText("");
        JFLocation.setText("");
        JFBalance.setText("");
        JFStoreName.setText("");
        JFPhoneNumber.setText("");
        JFPassword.setText("");
        
    }


}
