/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import Classes.Administrator;
import java.util.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JF_CustomerTopUp extends javax.swing.JFrame {
    
    double balance;
    String username;
    private Administrator admin;
    /**
     * Creates new form JF_CustomerTopUp
     */
    public JF_CustomerTopUp() {
        initComponents();
        JT_AddBalance.setVisible(false);
        JB_AddBalance.setVisible(false);
        JL_AddBalance.setVisible(false);
    }
    
    public JF_CustomerTopUp(Administrator admin) {
        this.admin = admin;
        initComponents();
        JT_AddBalance.setVisible(false);
        JB_AddBalance.setVisible(false);
        JL_AddBalance.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JT_Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JB_Search = new javax.swing.JButton();
        JL_Balance = new javax.swing.JLabel();
        JL_AddBalance = new javax.swing.JLabel();
        JT_AddBalance = new javax.swing.JTextField();
        JB_AddBalance = new javax.swing.JButton();
        JB_Back = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Customer Top Up");

        JT_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_UsernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Username:");

        JB_Search.setText("Search");
        JB_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SearchActionPerformed(evt);
            }
        });

        JL_AddBalance.setText("Add Balance:");

        JT_AddBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_AddBalanceActionPerformed(evt);
            }
        });

        JB_AddBalance.setText("Add");
        JB_AddBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddBalanceActionPerformed(evt);
            }
        });

        JB_Back.setText("Back");
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JB_Back)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JB_Search)
                                        .addComponent(JT_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(JL_Balance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_AddBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JT_AddBalance))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(JB_AddBalance)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JB_Back)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_AddBalance)
                    .addComponent(JT_AddBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_AddBalance)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_UsernameActionPerformed

    private void JB_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SearchActionPerformed
        // TODO add your handling code here:
        String Username = JT_Username.getText();
                
        String filePath = Config.getFilePath("UserListPath");
        File file = new File(filePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            Object[] tableLines = br.lines().toArray();
            boolean isUser = false;
            String balance = "";
            for(int i=0 ; i < tableLines.length ; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                if (dataRow[0].equals("Customer") && dataRow[1].equals(Username)){
                    balance = dataRow[5];
                    this.username = Username;
                    this.balance = Double.parseDouble(balance);
                    isUser = true;
                    JL_Balance.setText("Current Balance:  " + balance);
                    
                }else{
                    continue;
                    
                }

            }
            if (!isUser){
                    JL_Balance.setText("Customer not found");
                    this.username = "";
                    JT_AddBalance.setVisible(false);
                    JB_AddBalance.setVisible(false);
                    JL_AddBalance.setVisible(false);
            }else{
                    JT_AddBalance.setVisible(true);
                    JB_AddBalance.setVisible(true);
                    JL_AddBalance.setVisible(true);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"The Password doesn't match");
        }
    }//GEN-LAST:event_JB_SearchActionPerformed

    private void JT_AddBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_AddBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_AddBalanceActionPerformed

    private void JB_AddBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddBalanceActionPerformed
        // TODO add your handling code here:
        try{ 
            double AddBalance = Double.parseDouble(JT_AddBalance.getText());
            double balance = this.balance;
            String username = this.username;
            List<String> fileContent = new ArrayList<>();

            if (AddBalance == 0){
                JOptionPane.showMessageDialog(this, "Insert the amount");
            }else {
                JT_AddBalance.setVisible(false);
                JB_AddBalance.setVisible(false);
                JL_AddBalance.setVisible(false);
                balance = balance + AddBalance;

                JL_Balance.setText("Current Balance:  " + balance);

                String filePath = Config.getFilePath("UserListPath");
                File file = new File(filePath);

                try {
                    BufferedReader br = new BufferedReader(new FileReader(file));
                    Object[] tableLines = br.lines().toArray();

                    for(int i=0 ; i < tableLines.length ; i++){
                        String line = tableLines[i].toString().trim();
                        String[] dataRow = line.split("/");
                        if (dataRow[0].equals("Customer") && dataRow[1].equals(username)){
                            dataRow[5] = String.valueOf(balance);
                            line = String.join("/", dataRow);
                        }
                        fileContent.add(line);
                        JL_Balance.setText(username +"'s Balance:  " + balance);
                    }
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this,"The Password doesn't match");
                }
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
                    for (String updatedLine : fileContent) {
                        bw.write(updatedLine);
                        bw.newLine();
                    }
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error writing to the file: " + ex.getMessage());
                }
            }
        }catch (NumberFormatException ex) {
        // This block executes if parsing fails
        JOptionPane.showMessageDialog(this, "Please enter a valid number");
        }

        
        
    }//GEN-LAST:event_JB_AddBalanceActionPerformed

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame newFrame = new JF_Administrator(admin);
        newFrame.setVisible(true);
    }//GEN-LAST:event_JB_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_CustomerTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_CustomerTopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_AddBalance;
    private javax.swing.JButton JB_Back;
    private javax.swing.JButton JB_Search;
    private javax.swing.JLabel JL_AddBalance;
    private javax.swing.JLabel JL_Balance;
    private javax.swing.JTextField JT_AddBalance;
    private javax.swing.JTextField JT_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
