/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

/**
 *
 * @author USER
 */
public class RunnerLogin extends javax.swing.JFrame {

    /**
     * Creates new form RunnerLogin
     */
    public RunnerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        r_viewTask = new javax.swing.JButton();
        r_taskHistory = new javax.swing.JButton();
        r_customerReview = new javax.swing.JButton();
        r_revenue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Delivery Runner Home Page");

        r_viewTask.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r_viewTask.setText("View Task");
        r_viewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_viewTaskActionPerformed(evt);
            }
        });

        r_taskHistory.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r_taskHistory.setText("Task History");
        r_taskHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_taskHistoryActionPerformed(evt);
            }
        });

        r_customerReview.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r_customerReview.setText("Customer Review");
        r_customerReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_customerReviewActionPerformed(evt);
            }
        });

        r_revenue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r_revenue.setText("Revenue Dashboard");
        r_revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_revenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r_revenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r_customerReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r_taskHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r_viewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(r_viewTask)
                .addGap(18, 18, 18)
                .addComponent(r_taskHistory)
                .addGap(18, 18, 18)
                .addComponent(r_customerReview)
                .addGap(18, 18, 18)
                .addComponent(r_revenue)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_viewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_viewTaskActionPerformed
        // TODO add your handling code here:
        this.hide();
        RunnerTask rn=new RunnerTask();
        rn.show();
    }//GEN-LAST:event_r_viewTaskActionPerformed

    private void r_taskHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_taskHistoryActionPerformed
        // TODO add your handling code here:
        this.hide();
        RunnerHistory rh=new RunnerHistory();
        rh.show();
    }//GEN-LAST:event_r_taskHistoryActionPerformed

    private void r_customerReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_customerReviewActionPerformed
        // TODO add your handling code here:
        this.hide();
        RunnerReview rr=new RunnerReview();
        rr.show();
        
    }//GEN-LAST:event_r_customerReviewActionPerformed

    private void r_revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_revenueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_r_revenueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton r_customerReview;
    private javax.swing.JButton r_revenue;
    private javax.swing.JButton r_taskHistory;
    private javax.swing.JButton r_viewTask;
    // End of variables declaration//GEN-END:variables
}
