/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

/**
 *
 * @author USER
 */
public class RunnerTask extends javax.swing.JFrame {

    /**
     * Creates new form RunnerTask
     */
    public RunnerTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r_assignedtask = new javax.swing.JLabel();
        r_acceptTask = new javax.swing.JButton();
        r_declineTask = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        r_tasktable = new javax.swing.JTable();
        r_updateStatus = new javax.swing.JButton();
        r_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        r_assignedtask.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        r_assignedtask.setText("Assigned Task");

        r_acceptTask.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        r_acceptTask.setText("Accept");
        r_acceptTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_acceptTaskActionPerformed(evt);
            }
        });

        r_declineTask.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        r_declineTask.setText("Decline");
        r_declineTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_declineTaskActionPerformed(evt);
            }
        });

        r_tasktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "CustomerID", "Date", "VendorID", "FoodID", "Status"
            }
        ));
        jScrollPane1.setViewportView(r_tasktable);

        r_updateStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        r_updateStatus.setText("Update Status");
        r_updateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_updateStatusActionPerformed(evt);
            }
        });

        r_back.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        r_back.setText("Back");
        r_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r_acceptTask)
                .addGap(18, 18, 18)
                .addComponent(r_declineTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_updateStatus)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(r_back)
                        .addGap(176, 176, 176)
                        .addComponent(r_assignedtask))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(r_assignedtask)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(r_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_acceptTask)
                    .addComponent(r_declineTask)
                    .addComponent(r_updateStatus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_acceptTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_acceptTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_acceptTaskActionPerformed

    private void r_declineTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_declineTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_declineTaskActionPerformed

    private void r_updateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_updateStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_updateStatusActionPerformed

    private void r_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_backActionPerformed
        // TODO add your handling code here:
        this.hide();
        RunnerLogin rl=new RunnerLogin();
        rl.show();
        
    }//GEN-LAST:event_r_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton r_acceptTask;
    private javax.swing.JLabel r_assignedtask;
    private javax.swing.JButton r_back;
    private javax.swing.JButton r_declineTask;
    private javax.swing.JTable r_tasktable;
    private javax.swing.JButton r_updateStatus;
    // End of variables declaration//GEN-END:variables
}
