/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

/**
 *
 * @author vallerie
 */
public class VendorMain extends javax.swing.JFrame {

    /**
     * Creates new form VendorMain
     */
    public VendorMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_VendorHomePage = new javax.swing.JLabel();
        btn_Menu = new javax.swing.JButton();
        btn_CustReview = new javax.swing.JButton();
        btn_OrderHistory = new javax.swing.JButton();
        btn_RevDash = new javax.swing.JButton();
        btn_LogOut = new javax.swing.JButton();
        btn_OrderConfirmation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_VendorHomePage.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbl_VendorHomePage.setText("Vendor Home Page");

        btn_Menu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Menu.setText("Menu");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        btn_CustReview.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_CustReview.setText("Customer Review");
        btn_CustReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustReviewActionPerformed(evt);
            }
        });

        btn_OrderHistory.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_OrderHistory.setText("Order History");
        btn_OrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderHistoryActionPerformed(evt);
            }
        });

        btn_RevDash.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_RevDash.setText("Revenue Dashboard");
        btn_RevDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RevDashActionPerformed(evt);
            }
        });

        btn_LogOut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_LogOut.setText("Log Out");
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });

        btn_OrderConfirmation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_OrderConfirmation.setText("Order Confirmation");
        btn_OrderConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderConfirmationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_VendorHomePage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btn_LogOut))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_RevDash, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_CustReview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_OrderHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(btn_OrderConfirmation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(52, 52, 52)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_VendorHomePage)
                .addGap(28, 28, 28)
                .addComponent(btn_Menu)
                .addGap(18, 18, 18)
                .addComponent(btn_OrderConfirmation)
                .addGap(18, 18, 18)
                .addComponent(btn_OrderHistory)
                .addGap(18, 18, 18)
                .addComponent(btn_CustReview)
                .addGap(18, 18, 18)
                .addComponent(btn_RevDash)
                .addGap(37, 37, 37)
                .addComponent(btn_LogOut)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VendorAddItem af= new VendorAddItem();
        af.setVisible(true);
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_OrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderHistoryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VendorOrderHistory af= new VendorOrderHistory();
        af.setVisible(true);
    }//GEN-LAST:event_btn_OrderHistoryActionPerformed

    private void btn_CustReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustReviewActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        //VendorAddItem af= new VendorAddItem();
        //af.setVisible(true);
    }//GEN-LAST:event_btn_CustReviewActionPerformed

    private void btn_RevDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RevDashActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VendorRevDash af= new VendorRevDash();
        af.setVisible(true);
    }//GEN-LAST:event_btn_RevDashActionPerformed

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        //VendorLogin af= new VendorLogin();
        //af.setVisible(true);
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_OrderConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderConfirmationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VendorOrderConfirm af= new VendorOrderConfirm();
        af.setVisible(true);
    }//GEN-LAST:event_btn_OrderConfirmationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CustReview;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_OrderConfirmation;
    private javax.swing.JButton btn_OrderHistory;
    private javax.swing.JButton btn_RevDash;
    private javax.swing.JLabel lbl_VendorHomePage;
    // End of variables declaration//GEN-END:variables
}
